name: Issue Workflow
on: issues
jobs: 
    issue_job:
        runs-on: ubuntu-latest
        steps:
            - name: Check issues
              run: |
                echo "Issue event details:"
                echo "${{ toJson(github.event) }}"
