name: Issue Workflow
on: issues
jobs: 
    issue_job:
        runs-on: ubuntu-latest
        steps:
            - name: Check issues
              run: echo "An issue event has been triggered ${{ github.event}}"